package ch.uzh.ifi.hase.soprafs24.service;


import ch.uzh.ifi.hase.soprafs24.model.DrawCardResponse;
import ch.uzh.ifi.hase.soprafs24.model.NewDeckResponse;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

@Service
public class ExternalApiClientService {
    private final WebClient externalApiClient;

    public ExternalApiClientService(@Qualifier("externalApiClient") WebClient externalApiClient) {
        this.externalApiClient = externalApiClient;
    }

    /**
     * Gets the information generated by the deck of cards API (e.g. deck_id, success, etc.).
     * @return The information given by the deck of cards API.
     */
    public Mono<NewDeckResponse> createNewDeck() {
        return externalApiClient.get()
                .uri("/new/shuffle/?deck_count=1")
                .retrieve()
                .bodyToMono(NewDeckResponse.class);
    }

    /**
     * Draws the given amount of cards from a deck with the given deck id.
     * @param deckId The id of the deck from which to draw the cards.
     * @param cardAmount The amount of cards to be drawn.
     * @return The drawn cards.
     */
    public Mono<DrawCardResponse> drawCard(String deckId, int cardAmount) {
        return externalApiClient.get()
                .uri("/" + deckId + "/draw/?count=" + cardAmount)
                .retrieve()
                .bodyToMono(DrawCardResponse.class);
    }
}
