CREATE MEMORY TABLE "PUBLIC"."USER"(
    "ID" BIGINT NOT NULL,
    "AVATAR" INTEGER,
    "BIRTHDAY" DATE,
    "IS_GUEST" BOOLEAN NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "RATING" INTEGER NOT NULL,
    "STATUS" VARCHAR(255) NOT NULL,
    "TOKEN" VARCHAR(255),
    "USER_SETTINGS" VARCHAR(255) NOT NULL,
    "USERNAME" VARCHAR(255) NOT NULL
);